language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run coverage
  - npm run build
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
