// Copyright (c) 2026 The Jaeger Authors.
// SPDX-License-Identifier: Apache-2.0

import { defineConfig } from 'vite-plus';

export default defineConfig({
  fmt: {
    arrowParens: 'avoid',
    printWidth: 110,
    proseWrap: 'never',
    singleQuote: true,
    trailingComma: 'es5',
    sortPackageJson: false,
    ignorePatterns: [
      'packages/*/lib/',
      'packages/*/dist/',
      'packages/*/build/',
      'packages/jaeger-ui/index.d.ts',
      'scripts/release-notes.py',
      'scripts/draft-release.py',
      'docs/',
      'CHANGELOG.md',
      'RELEASE.md',
    ],
  },
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'jest', 'import'],
    jsPlugins: ['eslint-plugin-react-x'],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
      es2026: true,
    },
    ignorePatterns: [
      'packages/*/dist/**',
      'packages/*/lib/**',
      'packages/*/build/**',
      '**/node_modules/**',
      '**/.git/**',
      '**/.DS_Store',
      '**/coverage/**',
      '**/tsconfig.tsbuildinfo',
      '**/index.tsbuildinfo',
      '**/index.d.ts',
      '**/demo/**',
      'packages/jaeger-ui/src/api/v3/generated-client.ts',
      '**/*.cjs',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      // 'no-undef' disabled because tsc enforces this more accurately for .ts files,
      // and test globals (describe, it, expect, vi, etc.) are runtime-injected
      // by Vitest in .js files with no declaration file for the linter to see.
      'no-undef': 'off',
      'no-console': 'off',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'react/no-children-prop': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/no-new-array': 'error',
      'react-x/rules-of-hooks': 'error',
      'react-x/exhaustive-deps': 'error',
      'jest/no-disabled-tests': 'warn',
      'jest/no-focused-tests': 'error',
      'jest/no-identical-title': 'error',
      'jest/valid-title': 'error',
      'jest/valid-expect': 'error',
      'import/extensions': 'off',
      // Disabled because dynamic computed namespace access (e.g. track[fn]())
      // in parameterised tests is a false positive this rule cannot validate.
      'import/namespace': 'off',
    },
    overrides: [
      {
        files: ['**/*.{ts,tsx,mts}'],
        rules: {
          // TypeScript files: downgrade from top-level errors to warnings since
          // tsc already enforces these more precisely than the linter can.
          'no-redeclare': 'warn',
          'no-shadow': 'warn',
          'no-use-before-define': 'off',
          'no-useless-constructor': 'warn',
          'no-empty-function': 'off',
          'typescript/no-this-alias': 'off',
          'typescript/no-explicit-any': 'warn',
          'typescript/no-require-imports': 'warn',
          'typescript/no-restricted-types': 'warn',
          'typescript/no-empty-object-type': ['error', { allowObjectTypes: 'always' }],
          'typescript/no-unsafe-function-type': 'warn',
          'typescript/no-wrapper-object-types': 'warn',
          'typescript/ban-ts-comment': 'warn',
          'typescript/explicit-function-return-type': 'off',
          'typescript/explicit-module-boundary-types': 'off',
          'typescript/ban-types': 'off',
          'typescript/no-inferrable-types': 'off',
          'typescript/no-var-requires': 'off',
        },
      },
      {
        files: ['**/*.{js,jsx}'],
        rules: {
          // JavaScript/JSX files: fully disable rules that TypeScript handles for .ts files.
          // This override applies to all matched JS/JSX files in the repo, which tsc does not check.
          'no-unused-vars': 'off',
          'no-redeclare': 'off',
          'no-shadow': 'off',
          'no-use-before-define': 'off',
          'no-useless-constructor': 'off',
        },
      },
    ],
  },
});
