# Copyright (c) 2026 The Jaeger Authors.
# SPDX-License-Identifier: Apache-2.0
name: 'Setup Node and Deps'
description: 'Setup Node.js with corepack-managed pnpm and install dependencies'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: pnpm
        node-version-file: 'package.json'
    - run: corepack enable
      shell: bash
    - run: node --version && pnpm --version
      shell: bash
      env:
        COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'
    - run: pnpm install --frozen-lockfile
      shell: bash
      env:
        COREPACK_ENABLE_DOWNLOAD_PROMPT: '0'
