name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
      - name: Build
        run: |
          node --version
          yarn --version
          yarn install --frozen-lockfile
          yarn build
          find . -not -path '*/node_modules/*'
      - name: Archive
        uses: actions/upload-artifact@v1
        with:
          name: jaeger-ui
          path: packages/jaeger-ui/build/
