name: "Unit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: install yarn
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          echo $HOME/.yarn/bin >>"$GITHUB_PATH"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn coverage
      - run: yarn global add codecov
      - run: codecov
