# Fake "DCO check" workkflow inspired by https://github.com/onnx/onnx/pull/5398/files.
# The regular DCO check is required, but it does not from a merge queue and there is
# no way to configure it to run.
name: dco
on:
  merge_group:

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Fake DCO check to avoid blocking the merge queue"
