name: 'Lint and Build'

on:
  merge_group:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: npm
          node-version-file: 'package.json'
      - name: Upgrade npm
        run: |
          NPM_VERSION=$(node -p "require('./package.json').engines.npm.replace(/[^0-9.]/g, '')")
          npm install -g npm@$NPM_VERSION
      - run: npm --version
      - run: npm ci
      - name: Run depcheck
        run: npm run depcheck
      - run: npm run lint
      - run: npm run build
      - name: Ensure PR is not on main branch
        uses: jaegertracing/jaeger/.github/actions/block-pr-from-main-branch@main

  validate-3rd-party-configs:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          submodules: false

      - name: validate Forking Renovate Bot config
        run: |
          docker run \
            -v $PWD/renovate.json:/usr/src/app/renovate.json \
            ghcr.io/renovatebot/renovate:latest \
            renovate-config-validator

      - name: validate Codecov config
        run: |
          RESPONSE=$(curl -s --data-binary @.codecov.yml https://codecov.io/validate)
          echo "$RESPONSE"
          echo "$RESPONSE" | grep -q "Valid"
