name: Run and commit
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn install
     # - run: yarn workspace jaeger-ui upgrade caniuse-lite browserslist
     # - run: yarn workspace @jaegertracing/plexus upgrade caniuse-lite browserslist
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
