name: 'Unit Tests'

on:
  merge_group:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ (github.event.pull_request && github.event.pull_request.number) || github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup-node-and-deps
      - run: npm run coverage
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          verbose: true
          # Using upload token helps against rate limiting errors.
          # Cannot define it as secret as we need it accessible from forks.
          # See https://github.com/codecov/codecov-action/issues/837
          token: 31c3122b-7b49-4267-a117-8c9354a97119
